# site_name: My Docs
# site_url: https://joul2.github.io/docs/
# site_author: joul2
# theme:
#   name: material

# yaml不支持多行注释

# git config --global user.email "2019285695@qq.com"

# git config --global user.name "joul"

# 取消代理设置
# git config --global --unset http.proxy 
# git config --global --unset https.proxy

# 注意修改成自己的IP和端口号
# git config --global http.proxy http://127.0.0.1:7890 
# git config --global https.proxy http://127.0.0.1:7890

# mkdocs build
# mkdocs serve
# mkdocs gh-deploy

site_name: 我的第一个站点
theme:
  language: zh


  name: material

  features: 
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant 
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    # - content.action.edit
    # - content.action.view
    - content.code.annotate 

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 切换到暗色模式

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换到暗色模式
  icon: 
    repo: fontawesome/brands/github #右上角图标
  
# edit_uri: edit/main/docs # 编辑按钮跳转的链接 
repo_url: https://github.com/joul2/docs # 右上角点击跳转的链接
repo_name: joul2.github.io # 右上角的名字

nav:
- 首页: index.md
- 集成电路科学与工程: 
    - 研究生入学推荐书目: 集成电路科学与工程/books.md
    - 电类基础:
        - 电路基础: 集成电路科学与工程/电类基础/电路基础.md
        - 信号与系统: 集成电路科学与工程/电类基础/信号与系统.md
        - 半导体物理与器件原理: 集成电路科学与工程/电类基础/半导体物理与器件原理.md
        - 数字电子技术: 集成电路科学与工程/电类基础/数字电子技术.md
        - 模拟电子技术: 集成电路科学与工程/电类基础/模拟电子技术.md
    - 数集理论:
        - verilog: 集成电路科学与工程/数字集成电路设计基础/数字逻辑与verilog设计.md
        - 数字集成电路设计透视: 集成电路科学与工程/数字集成电路设计基础/数字集成电路设计透视.md
    - 模集理论:
        - 模拟CMOS集成电路设计: 集成电路科学与工程/模拟集成电路设计基础/模拟CMOS集成电路设计.md
    - 数字IC设计:
        - tcl: 集成电路科学与工程/数字IC设计/tcl.md
        - 数集大作业: 集成电路科学与工程/数字IC设计/数集大作业.md
        - 本科毕设: 集成电路科学与工程/数字IC设计/本科毕设.md
    - 模拟IC设计:
        - 模集大作业: 集成电路科学与工程/模拟IC设计/模集大作业.md
    - 验证:
        - System Verilog: 集成电路科学与工程/验证/System Verilog.md
        - UVM: 集成电路科学与工程/验证/UVM.md
    - 数字后端:
        - 数字后端: 集成电路科学与工程/数字后端/数字后端.md
- 人工智能:
    - 三维视觉: 
        - SLAM: 人工智能/三维视觉/SLAM.md
        - 配准: 人工智能/三维视觉/3DvisionReg.md
        - PCL: 人工智能/三维视觉/PCL.md
    - 基地项目: 
        - 物流车: 人工智能/基地项目/物流车.md
        - 智能分拣: 人工智能/基地项目/智能分拣.md
        - 机械臂: 人工智能/基地项目/机械臂.md
        - ROS: 人工智能/基地项目/ROS.md
        - opencv: 人工智能/基地项目/opencv.md
    - 计科基础课:
        - 数据结构: 人工智能/计科基础课/数据结构.md
        - 数字逻辑: 人工智能/计科基础课/数字逻辑.md
        - 计算机组成与系统结构: 人工智能/计科基础课/计算机组成与系统结构.md
        - 计算机操作系统: 人工智能/计科基础课/计算机操作系统.md
        - 计算机网络: 人工智能/计科基础课/计算机网络.md
    - 机器学习:
        - 机器学习: 人工智能/机器学习/机器学习.md
    - GPU并行计算:
        - CUDA: 人工智能/GPU并行计算/CUDA.md
- 语言:
    - 编程:
        - C: 语言/编程/C.md
        - C++: 语言/编程/C++.md
        - C#: 语言/编程/C#.md
        - Python: 语言/编程/python.md
        - Java: 语言/编程/java.md
        - makefile: 语言/编程/makefile.md
        - html: 语言/编程/html.md
        - css: 语言/编程/css.md
        - sql: 语言/编程/sql.md
    - 交流:
        - 英语: 语言/交流/日语.md
        - 日语: 语言/交流/英语.md
        - 西班牙语: 语言/交流/西班牙语.md
# extra:
#   social: 
#   - icon: fontawesome/brands/github
#     link: https://joul2.github.io/
#     name: Github
#   - icon: fontawesome/brands/bilibili
#     link: https://joul2.github.io/
#     name: Bilibili
#   - icon: material/email
#     link: joul:<2019285695@qq.com>
#     name: E-mail
